In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from scipy.stats import skew
from scipy.stats import norm
from scipy import stats

In [3]:
train_data_hdb = pd.read_csv('./data/hdb_train.csv')

In [7]:
train_data_hdb.shape
print "List of Columns:\n", ", ".join(train_data_hdb.columns), "\n\n"
train_data_hdb.head(10)

List of Columns:
index, block, flat_model, flat_type, floor_area_sqm, lease_commence_date, month, resale_price, storey_range, street_name, town, latitude, longitude, postal_code, floor

,index,block,flat_model,flat_type,floor_area_sqm,lease_commence_date,month,resale_price,storey_range,street_name,town,latitude,longitude,postal_code,floor
0,0,309,IMPROVED,1 ROOM,31.0,1977,1990-01,9000.0,10 TO 12,ANG MO KIO AVE 1,ANG MO KIO,1.365029,103.845300,562309,11
1,1,309,IMPROVED,1 ROOM,31.0,1977,1990-01,6000.0,04 TO 06,ANG MO KIO AVE 1,ANG MO KIO,1.365029,103.845300,562309,5
2,2,309,IMPROVED,1 ROOM,31.0,1977,1990-01,8000.0,10 TO 12,ANG MO KIO AVE 1,ANG MO KIO,1.365029,103.845300,562309,11
3,3,309,IMPROVED,1 ROOM,31.0,1977,1990-01,6000.0,07 TO 09,ANG MO KIO AVE 1,ANG MO KIO,1.365029,103.845300,562309,8
4,4,216,NEW GENERATION,3 ROOM,73.0,1976,1990-01,47200.0,04 TO 06,ANG MO KIO AVE 1,ANG MO KIO,1.366197,103.841505,560216,5
5,5,211,NEW GENERATION,3 ROOM,67.0,1977,1990-01,46000.0,01 TO 03,ANG MO KIO AVE 3,ANG MO KIO,1.369197,103.841667,560211,2
6,6,202,NEW GENERATION,3 ROOM,67.0,1977,1990-01,42000.0,07 TO 09,ANG MO KIO AVE 3,ANG MO KIO,1.368446,103.844516,560202,8
7,7,235,NEW GENERATION,3 ROOM,67.0,1977,1990-01,38000.0,10 TO 12,ANG MO KIO AVE 3,ANG MO KIO,1.366824,103.836491,560235,11
8,8,235,NEW GENERATION,3 ROOM,67.0,1977,1990-01,40000.0,04 TO 06,ANG MO KIO AVE 3,ANG MO KIO,1.366824,103.836491,560235,5
9,9,232,NEW GENERATION,3 ROOM,67.0,1977,1990-01,47000.0,01 TO 03,ANG MO KIO AVE 3,ANG MO KIO,1.368346,103.837196,560232,2

In [12]:
train_data_hdb.flat_model.value_counts()

MODEL A                   206670
IMPROVED                  200096
NEW GENERATION            167960
SIMPLIFIED                 51321
STANDARD                   37531
APARTMENT                  29339
PREMIUM APARTMENT          28147
MAISONETTE                 24950
MODEL A2                    8296
ADJOINED FLAT               1880
MODEL A-MAISONETTE          1773
TERRACE                      604
DBSS                         491
MULTI GENERATION             466
TYPE S1                      173
IMPROVED-MAISONETTE          104
PREMIUM MAISONETTE            74
TYPE S2                       74
2-ROOM                        38
PREMIUM APARTMENT LOFT         5
Name: flat_model, dtype: int64

In [13]:
train_data_hdb.flat_type.value_counts()

4 ROOM              282423
3 ROOM              255151
5 ROOM              154655
EXECUTIVE            57612
2 ROOM                8441
1 ROOM                1244
MULTI GENERATION       466
Name: flat_type, dtype: int64

In [20]:
train_data_hdb.floor.value_counts()

5     194143
8     177498
2     156862
11    147820
14     46014
17     16621
20      8231
23      5238
3       2700
26      2050
13      1259
29       749
18       265
35       141
32       139
38       135
41        61
28        39
47        11
44         9
50         5
33         2
Name: floor, dtype: int64

In [22]:
train_data_hdb['resale_price'].describe()

count    7.599920e+05
mean     2.814338e+05
std      1.414466e+05
min      5.000000e+03
25%      1.750000e+05
50%      2.630000e+05
75%      3.680000e+05
max      1.180000e+06
Name: resale_price, dtype: float64

In [27]:
sns.distplot(train_data_hdb['resale_price'] , fit=norm);

# Get the fitted parameters used by the function
(mu, sigma) = norm.fit(train_data_hdb['resale_price'])
print( '\n mu = {:.2f} and sigma = {:.2f}\n'.format(mu, sigma))
plt.legend(['Normal dist. ($\mu=$ {:.2f} and $\sigma=$ {:.2f} )'.format(mu, sigma)],
            loc='best')
plt.ylabel('Frequency')
plt.title('SalePrice distribution')

fig = plt.figure()
res = stats.probplot(train_data_hdb['resale_price'], plot=plt)
plt.show()

print("Skewness: %f" % train_data_hdb['resale_price'].skew())
print("Kurtosis: %f" % train_data_hdb['resale_price'].kurt())

 mu = 281433.84 and sigma = 141446.49

NameError: name 'stats' is not defined